title: MaxBlo.ga
description: My Blog and Notes
author: Hristo Jelev
logo: /static/img/avatar2.jpg
github: https://github.com/hjelev
about: maxblo.ga

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: free-apps
google_analytics: 


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
